/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;


import Pendaftaran.PendaftaranController;


/**
 *
 * @author Lenovo
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }
    
    private HomeController cbt = new HomeController();
    private PendaftaranController con = new PendaftaranController();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dHome = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFilePendaftaran = new javax.swing.JMenuItem();
        menuFilePembayaran = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanPendaftaran = new javax.swing.JMenuItem();
        menuLaporanPembayaran = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Uniska");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout dHomeLayout = new javax.swing.GroupLayout(dHome);
        dHome.setLayout(dHomeLayout);
        dHomeLayout.setHorizontalGroup(
            dHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dHomeLayout.setVerticalGroup(
            dHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuFilePendaftaran.setText("Pendaftaran");
        menuFilePendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilePendaftaranActionPerformed(evt);
            }
        });
        menuFile.add(menuFilePendaftaran);

        menuFilePembayaran.setText("Pembayaran");
        menuFilePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilePembayaranActionPerformed(evt);
            }
        });
        menuFile.add(menuFilePembayaran);

        jMenuBar1.add(menuFile);

        menuLaporan.setText("Laporan");

        menuLaporanPendaftaran.setText("Pendaftaran");
        menuLaporanPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPendaftaranActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanPendaftaran);

        menuLaporanPembayaran.setText("Pembayaran");
        menuLaporanPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPembayaranActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanPembayaran);

        jMenuBar1.add(menuLaporan);

        jMenu1.setText("User");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menu.setText("...");

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menu.add(menuKeluar);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        cbt.keluar(this);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cbt.maximaze(this);
    }//GEN-LAST:event_formWindowOpened

    private void menuFilePendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilePendaftaranActionPerformed
        cbt.menu_pendaftaran(this);
    }//GEN-LAST:event_menuFilePendaftaranActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed

    }//GEN-LAST:event_menuFileActionPerformed

    private void menuFilePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilePembayaranActionPerformed
        cbt.menu_pembayaran(this);
    }//GEN-LAST:event_menuFilePembayaranActionPerformed

    private void menuLaporanPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPendaftaranActionPerformed
        cbt.menu_Laporan(this);
    }//GEN-LAST:event_menuLaporanPendaftaranActionPerformed

    private void menuLaporanPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPembayaranActionPerformed
        cbt.menu_Laporan_Pembayaran(this);
    }//GEN-LAST:event_menuLaporanPembayaranActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cbt.logout(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dHome;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFilePembayaran;
    private javax.swing.JMenuItem menuFilePendaftaran;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanPembayaran;
    private javax.swing.JMenuItem menuLaporanPendaftaran;
    // End of variables declaration//GEN-END:variables
}
